services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - '8080:80'
    volumes:
      - ./app:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      dockerfile: ./etc/docker/php-fpm.Dockerfile
    volumes:
      - ./app:/app
    links:
      - composer

  php-cli:
    container_name: php-cli
    build:
      dockerfile: ./etc/docker/php-cli.Dockerfile
    volumes:
      - ./app:/app
    links:
      - composer

  composer:
    container_name: composer
    image: composer
    volumes:
      - ./app:/app
    entrypoint:
      - composer
      - install
