services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      dockerfile: ./etc/docker/php-fpm.Dockerfile
    volumes:
      - ./app:/var/www/app
    links:
      - composer
  composer:
    image: composer
    volumes:
      - ./app:/app
    entrypoint:
      - composer
      - install
